# Generated by Django 4.0.4 on 2022-06-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=40)),
                ('telephone', models.IntegerField()),
                ('code_postal', models.IntegerField()),
                ('due_date', models.DateField()),
                ('is_delivered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('telephone', models.IntegerField()),
                ('respuesto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesto', models.CharField(max_length=40)),
            ],
        ),
    ]
